name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 

      - name: Set up Node.js (optional, for build steps)
        uses: actions/setup-node@v2
        with:
          node-version: '18' 

      - name: Set git user info
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Set git remote URL
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git  # Ensure correct token usage

      - name: Build your project (optional, if you need to build first)
        run: |
          # Add your build commands here (e.g., npm run build for Node.js projects)
          echo "Building project..."

      - name: Commit changes to GitHub Pages (push to main branch)
        run: |
          git add .  # Stage changes
          git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"  # Avoid failure if no changes to commit
          git push origin main  # Push to main branch (GitHub Pages serves content from here)
